services:
  manage_motor_fe:
    build: .
    image: vantablackj/motor-manage-fe:latest
    ports:
      - "3000:80"
    restart: always
    container_name: manage_motor_fe_container
    environment:
      - NODE_ENV=production
