apiVersion: v1
kind: Service
metadata:
  name: motor-fe-service
spec:
  type: ClusterIP
  ports:
    - port: 80 # Cổng của Service FE
      targetPort: 80 # Cổng Nginx bên trong Container
  selector:
    app: motor-fe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: motor-fe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: motor-fe
  template:
    metadata:
      labels:
        app: motor-fe
    spec:
      containers:
        - name: motor-fe
          image: vantablackj/motor-fe:v11
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      imagePullSecrets:
        - name: dockerhub-secret
